env:
  es6: true
  node: true
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - import
  - plugin:@typescript-eslint/recommended-requiring-type-checking
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  ecmaVersion: 11
  sourceType: module
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - dist/*
  - nod_modules/*
rules:
  no-restricted-syntax: ['off']
  import/extensions: ['error', 'never']
  lines-between-class-members: ["error", "always", { exceptAfterSingleLine: true }]
  class-methods-use-this: ['off']
  import/no-cycle: ['off']
  '@typescript-eslint/no-unsafe-assignment': ['off']
settings:
  import/resolver:
    node:
      extensions:
        - .ts
