env:
  es6: true
  node: true
extends:
  - airbnb-base
  - import
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
ignorePatterns:
  - dist/*
  - node_modules/*
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  project: ./tsconfig.json
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-explicit-any':
    - off
  '@typescript-eslint/no-floating-promises':
    - off
  '@typescript-eslint/no-unsafe-assignment':
    - off
  guard-for-in:
    - off
  no-await-in-loop:
    - off
  class-methods-use-this:
    - off
  import/extensions:
    - error
    - never
  import/no-cycle:
    - off
  lines-between-class-members:
    - error
    - always
    - exceptAfterSingleLine: true
  no-restricted-syntax:
    - off
  max-len:
    - error
    - 120
  no-multiple-empty-lines:
    - error
    - max: 1
      maxEOF: 1
      maxBOF: 0
settings:
  import/resolver:
    node:
      extensions:
        - .ts
