env:
  es6: true
  node: true
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  # - eslint:recommended
  # - plugin:import/errors
  # - plugin:import/warnings
  # - plugin:import/typescript
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - dist/*
  - nod_modules/*
rules:
  import/extensions: ['error', 'never']
settings:
  import/resolver:
    node:
      extensions:
        - .ts
