env:
  es6: true
  node: true
extends:
  - plugin:@typescript-eslint/recommended
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - dist/*
  - nod_modules/*
settings:
  import/resolver:
    node:
      extensions:
        - .ts
