env:
  es6: true
  node: true
extends:
  - airbnb-base
  - import
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - prettier/@typescript-eslint
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
ignorePatterns:
  - dist/*
  - node_modules/*
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  project: ./tsconfig.json
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-unsafe-assignment':
    - off
  class-methods-use-this:
    - off
  import/extensions:
    - error
    - never
  import/no-cycle:
    - off
  lines-between-class-members:
    - error
    - always
    - exceptAfterSingleLine: true
  no-restricted-syntax:
    - off
settings:
  import/resolver:
    node:
      extensions:
        - .ts
